main: org.chibbi.geobasedWeather.App
name: "geobasedWeather"
version: 1.0.0
api-version: 1.16
author: "chibbi"
description: "let your minecraft weather be the same, as your real life weather."
website: "www.spigotmc.org"
commands:
   weather:
      description: "configurate your weather"
      permission: rolePlay.weather
permissions:
   rolePlay.weather:
      description: Permission for the /weather command
      default: op